version: "2.0"

services:
    
    db:
        image: mysql:5.7
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports: 
            - 3306:3306
        volumes: 
            - /var/lib/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: portal_noticias